import {database,initialise,getSettings,needUser,mergeCart,cartOwner,identity,id,now,parse,assert,HttpError,runtimeEnv} from './server';
import {ticketPrice,packageSaving} from './pricing';
import {bookingSchema,checkoutSchema} from './validation';
import type {BookingInput,CartItem,EventRecord,Product,Variant,Order} from './types';
import type {Settings} from './config';
import {queueOrderEmails} from './emails';
export type QuoteLine={cartId:string;kind:string;referenceId:string;name:string;quantity:number;unit:number;total:number;image:string;data:Record<string,unknown>};
export type Resource={kind:'event'|'variant';id:string;quantity:number};
export async function membership(){const u=await identity();if(!u)return false;const row=await database().prepare("SELECT status,expires_at FROM memberships WHERE user_id=? AND status='active'").bind(u.userId).first<{status:string,expires_at:string|null}>();return !!row&&(!row.expires_at||row.expires_at>now());}
export async function getCart(){await initialise();const owner=await cartOwner();if(!owner)return [];return(await database().prepare('SELECT * FROM cart_items WHERE owner=? ORDER BY created_at').bind(owner).all<CartItem>()).results;}
export async function addCart(input:Record<string,unknown>){await initialise();const owner=await cartOwner(true);assert(owner,'Unable to open your basket.');let data:unknown={};let reference=String(input.referenceId||'');let quantity=Number(input.quantity||1);assert(Number.isInteger(quantity)&&quantity>=1&&quantity<=20,'Choose between 1 and 20 items.');const kind=input.kind;
 if(kind==='booking'){data=bookingSchema.parse(input.data);reference=(data as BookingInput).eventId;quantity=1;await quoteBooking(data as BookingInput,await getSettings(),await membership(),0);}
 else if(kind==='product'){const row=await database().prepare('SELECT v.*,p.active FROM variants v JOIN products p ON p.id=v.product_id WHERE v.id=?').bind(reference).first<Variant&{active:number}>();assert(row&&row.active,'This product is unavailable.');assert(row.stock-row.reserved>=quantity,'This size is currently unavailable. Please choose another.');}
 else if(kind==='gift'){const raw=input.data as Record<string,unknown>;const amount=Number(raw?.amount);assert(Number.isInteger(amount)&&amount>=500&&amount<=100000,'Gift cards must be between £5 and £1,000.');data={amount,recipientName:String(raw?.recipientName||'').slice(0,100),recipientEmail:String(raw?.recipientEmail||'').slice(0,254),message:String(raw?.message||'').slice(0,500),giftType:String(raw?.giftType||'General gift card').slice(0,80)};reference='gift';}
 else throw new HttpError('Choose an experience, product or gift card.');
 const cartId=id();await database().prepare('INSERT INTO cart_items (id,owner,kind,reference_id,quantity,data,created_at) VALUES (?,?,?,?,?,?,?)').bind(cartId,owner,kind,reference,quantity,JSON.stringify(data),now()).run();return {id:cartId,count:(await getCart()).length};
}
export async function removeCart(cartId:string){const owner=await cartOwner();assert(owner,'Your basket is empty.');await database().prepare('DELETE FROM cart_items WHERE id=? AND owner=?').bind(cartId,owner).run();}
export async function quoteBooking(data:BookingInput,s:Settings,member:boolean,promo:number){const event=await database().prepare('SELECT * FROM events WHERE id=?').bind(data.eventId).first<EventRecord>();assert(event,'This experience is no longer available.');assert(event.status==='open','This experience is cancelled or not currently open for booking.');assert(event.date>=new Date().toLocaleDateString('en-CA',{timeZone:s.timeZone}),'This event has already taken place.');assert(event.capacity-event.reserved>=data.adults+data.children,'There are not enough seats remaining. Please reduce your group size or choose another date.');const cooking=event.type==='Cooking class';assert(!cooking||data.children===0,'Children’s tickets are not available for this cooking class.');assert(!data.guests.some(g=>g.photography)||data.privatePhotographyConsent,'Please confirm private photography delivery consent for the photography package.');
 const resources:Resource[]=[{kind:'event',id:event.id,quantity:data.adults+data.children}];let total=data.children*s.childPrice;
 const guests=[];
 for(const g of data.guests){const ticket=cooking?{price:event.price,percent:0,type:'standard'}:ticketPrice(event.price,g.discounts,s,member,promo);let price=ticket.price;let clothing:null|{variant:Variant;product:Product}=null;
 if(g.clothing){const variant=await database().prepare('SELECT * FROM variants WHERE id=?').bind(g.clothing).first<Variant>();assert(variant,'Please choose an available garment.');const product=await database().prepare("SELECT * FROM products WHERE id=? AND category='Clothing' AND active=1").bind(variant.product_id).first<Product>();assert(product&&product.price===s.clothingPrice,'This garment is not available for the clothing experience.');assert(variant.stock-variant.reserved>=1,'Your selected garment size has sold out. Please choose another.');clothing={variant,product};resources.push({kind:'variant',id:variant.id,quantity:1});price+=s.clothingPrice;}
 if(g.photography)price+=s.photographyPrice;
 const extraSaving=cooking?0:packageSaving(event.price-ticket.price,!!g.clothing&&g.photography,s)-(event.price-ticket.price);price-=extraSaving;
 total+=price;guests.push({...g,ticketPrice:ticket.price,discount:ticket.type,discountPercent:ticket.percent,clothing,price,packageSaving:extraSaving});}
 return {event,total,resources,guests};
}
export async function quoteCart(promoCode=''){const items=await getCart();const s=await getSettings();const member=await membership();let promo=0;if(promoCode){const row=await database().prepare('SELECT * FROM promo_codes WHERE code=? AND active=1 AND expires_at>=?').bind(promoCode.trim().toUpperCase(),now().slice(0,10)).first<{percent:number}>();assert(row,'This promo code is invalid or has expired.');promo=row.percent;}
 const lines:QuoteLine[]=[];const resources:Resource[]=[];
 for(const item of items){if(item.kind==='booking'){const data=bookingSchema.parse(parse(item.data));const q=await quoteBooking(data,s,member,promo);resources.push(...q.resources);lines.push({cartId:item.id,kind:'booking',referenceId:q.event.id,name:q.event.title,quantity:1,unit:q.total,total:q.total,image:q.event.image,data:{...data,event:q.event,guestPrices:q.guests}});}
 if(item.kind==='product'){const v=await database().prepare('SELECT * FROM variants WHERE id=?').bind(item.reference_id).first<Variant>();assert(v,'An item in your basket is unavailable.');const p=await database().prepare('SELECT * FROM products WHERE id=? AND active=1').bind(v.product_id).first<Product>();assert(p,'An item in your basket is no longer on sale.');assert(v.stock-v.reserved>=item.quantity,`${p.name} has insufficient stock in ${v.size}.`);const unit=v.price??p.sale_price??p.price;lines.push({cartId:item.id,kind:'product',referenceId:v.id,name:p.name+' · '+v.label,quantity:item.quantity,unit,total:unit*item.quantity,image:p.image,data:{variant:v,product:p}});resources.push({kind:'variant',id:v.id,quantity:item.quantity});}
 if(item.kind==='gift'){const data=parse<{amount:number,recipientName:string,recipientEmail:string,message:string,giftType:string}>(item.data);assert(Number.isInteger(data.amount)&&data.amount>=500&&data.amount<=100000,'Gift card amount is invalid.');lines.push({cartId:item.id,kind:'gift',referenceId:'gift',name:data.giftType,quantity:item.quantity,unit:data.amount,total:data.amount*item.quantity,image:'/images/textiles.webp',data});}}
 const merged=new Map<string,Resource>();for(const r of resources){const key=r.kind+':'+r.id;const existing=merged.get(key);merged.set(key,{...r,quantity:r.quantity+(existing?.quantity||0)});}
 for(const r of merged.values()){const row=r.kind==='event'?await database().prepare('SELECT capacity-reserved AS available FROM events WHERE id=?').bind(r.id).first<{available:number}>():await database().prepare('SELECT stock-reserved AS available FROM variants WHERE id=?').bind(r.id).first<{available:number}>();assert(row&&row.available>=r.quantity,'There is not enough availability for all the items in your basket. Please review your quantities.');}
 return {lines,resources:Array.from(merged.values()),subtotal:lines.reduce((sum,l)=>sum+l.total,0),member,settings:s};
}
function guard(db:D1Database,label:string){return db.prepare('INSERT INTO operation_guards (id,ok) VALUES (?,changes())').bind(label);}
export async function checkout(raw:unknown){const input=checkoutSchema.parse(raw);const u=await mergeCart();await releaseExpired();const db=database();const orderId=input.idempotencyKey;
 const existing=await db.prepare('SELECT * FROM orders WHERE id=? AND user_id=?').bind(orderId,u.userId).first<Order>();if(existing)return existing.status==='pending'?createStripeSession(existing):{orderId:existing.id,reference:existing.reference,demo:!!existing.demo};
 const q=await quoteCart(input.promoCode);assert(q.lines.length,'Your basket is empty.');const s=q.settings;
 assert(input.demo===s.demoMode,'Checkout mode changed. Refresh and try again.');if(!input.demo){assert(s.launchReady&&runtimeEnv().STRIPE_SECRET_KEY&&runtimeEnv().STRIPE_WEBHOOK_SECRET,'Live booking is not open yet.');assert(!q.lines.some(l=>(l.data.event as EventRecord|undefined)?.demo||(l.data.product as Product|undefined)?.demo),'Demo experiences and products cannot be purchased with real payments.');}
 if(input.failure)throw new HttpError('Demo payment declined. No booking was created and your basket is saved. Please try again.',402);
 assert(input.delivery!=='shipping'||s.shippingEnabled,'Shipping is not available yet. Choose collection.');assert(input.delivery!=='shipping'||input.address.trim().length>10,'Please enter a full delivery address.');
 const shipping=input.delivery==='shipping'&&q.lines.some(l=>l.kind==='product')?s.shippingPrice:0;let giftApplied=0;const giftCode=input.giftCode.trim().toUpperCase();
 if(giftCode){assert(!q.lines.some(l=>l.kind==='gift'),'Gift cards cannot be used to purchase gift cards.');const gift=await db.prepare("SELECT * FROM gift_cards WHERE code=? AND status='active' AND demo=?").bind(giftCode,input.demo?1:0).first<{balance:number}>();assert(gift&&gift.balance>0,'This gift card is unavailable or has no balance.');giftApplied=Math.min(gift.balance,q.subtotal+shipping);}
 const total=q.subtotal+shipping-giftApplied;const reference='NIM-'+id().slice(0,8).toUpperCase();const stamp=now();const expires=Date.now()+35*60*1000;
 const statements=[db.prepare('INSERT INTO orders (id,reference,user_id,status,total,currency,contact,delivery,created_at,demo,expires_at,gift_code,gift_applied,promo_code) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(orderId,reference,u.userId,'pending',total,'GBP',JSON.stringify(input.contact),JSON.stringify({method:input.delivery,address:input.address,shipping}),stamp,input.demo?1:0,expires,giftCode||null,giftApplied,input.promoCode||null)];
 if(giftApplied){statements.push(db.prepare('UPDATE gift_cards SET balance=balance-? WHERE code=? AND balance>=? AND status=?').bind(giftApplied,giftCode,giftApplied,'active'),guard(db,orderId+'-gift'));}
 q.resources.forEach((r,i)=>{statements.push(r.kind==='event'?db.prepare("UPDATE events SET reserved=reserved+? WHERE id=? AND status='open' AND reserved+?<=capacity").bind(r.quantity,r.id,r.quantity):db.prepare('UPDATE variants SET reserved=reserved+? WHERE id=? AND reserved+?<=stock').bind(r.quantity,r.id,r.quantity));statements.push(guard(db,orderId+'-'+i));statements.push(db.prepare('INSERT INTO reservations (id,order_id,kind,resource_id,quantity) VALUES (?,?,?,?,?)').bind(id(),orderId,r.kind,r.id,r.quantity));});
 for(const line of q.lines){statements.push(db.prepare('INSERT INTO order_items (id,order_id,kind,reference_id,name,quantity,price,data) VALUES (?,?,?,?,?,?,?,?)').bind(id(),orderId,line.kind,line.referenceId,line.name,line.quantity,line.unit,JSON.stringify(line.data)));
 if(line.kind==='booking'){const b=line.data as unknown as BookingInput&{guestPrices:Array<Record<string,unknown>>};const bookingId=id();statements.push(db.prepare('INSERT INTO bookings (id,reference,user_id,event_id,order_id,adults,children,status,total,details,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(bookingId,'B-'+id().slice(0,8).toUpperCase(),u.userId,line.referenceId,orderId,b.adults,b.children,'pending',line.total,JSON.stringify({dietary:b.dietary,allergies:b.allergies,accessibility:b.accessibility,marketingConsent:b.marketingConsent}),stamp));
 b.guestPrices.forEach((g,i)=>statements.push(db.prepare('INSERT INTO booking_guests (id,booking_id,name,ticket_type,discount,price,details) VALUES (?,?,?,?,?,?,?)').bind(id(),bookingId,g.name||`Adult ${i+1}`,'adult',g.discount,g.ticketPrice,JSON.stringify(g))));for(let n=0;n<b.children;n++)statements.push(db.prepare('INSERT INTO booking_guests (id,booking_id,name,ticket_type,discount,price,details) VALUES (?,?,?,?,?,?,?)').bind(id(),bookingId,`Child ${n+1}`,'child','fixed',s.childPrice,'{}'));
 if(b.guests.some(g=>g.photography))statements.push(db.prepare('INSERT INTO photography_orders (id,booking_id,user_id,marketing_consent,private_consent) VALUES (?,?,?,?,?)').bind(id(),bookingId,u.userId,b.marketingConsent?1:0,b.privatePhotographyConsent?1:0));}}
 statements.push(db.prepare('DELETE FROM operation_guards WHERE id LIKE ?').bind(orderId+'-%'));
 try{await db.batch(statements);}catch(e){console.error('Reservation rejected',e);throw new HttpError('Availability changed while you were checking out. Your basket is saved; please review it and try again.',409);}
 if(input.demo||total===0){await completeOrder(orderId,input.demo?'demo_confirmed':'paid',null);await clearPurchasedCart(u.userId,q.lines.map(l=>l.cartId));return {orderId,reference,demo:input.demo};}
 const order=await db.prepare('SELECT * FROM orders WHERE id=?').bind(orderId).first<Order>();assert(order,'Unable to find your pending order.');return createStripeSession(order);
}
async function clearPurchasedCart(owner:string,cartIds:string[]){if(cartIds.length)await database().batch(cartIds.map(cartId=>database().prepare('DELETE FROM cart_items WHERE id=? AND owner=?').bind(cartId,owner)));}
export async function createStripeSession(order:Order){const key=String(runtimeEnv().STRIPE_SECRET_KEY||'');assert(key,'Payment provider is not connected.',503);const s=await getSettings();if(order.payment_id){const existing=await fetch('https://api.stripe.com/v1/checkout/sessions/'+encodeURIComponent(order.payment_id),{headers:{Authorization:'Bearer '+key}}).then(r=>r.json()) as {url?:string,payment_status:string};if(existing.url)return {url:existing.url,orderId:order.id};if(existing.payment_status==='paid')return {orderId:order.id,reference:order.reference};}
 const body=new URLSearchParams({mode:'payment',success_url:s.siteUrl+'/checkout/success?order='+order.id,cancel_url:s.siteUrl+'/checkout?cancelled=1&order='+order.id,client_reference_id:order.id,customer_email:parse<{email:string}>(order.contact).email,'line_items[0][price_data][currency]':'gbp','line_items[0][price_data][unit_amount]':String(order.total),'line_items[0][price_data][product_data][name]':'Nimontron · '+order.reference,'line_items[0][quantity]':'1','metadata[order_id]':order.id,'payment_intent_data[metadata][order_id]':order.id,expires_at:String(Math.floor(new Date(order.created_at).getTime()/1000)+2100)});
 try{const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':order.id},body,signal:AbortSignal.timeout(15000)});const data=await response.json() as {id?:string,url?:string,error?:{message:string}};if(!response.ok||!data.id||!data.url)throw new Error(data.error?.message||'Checkout session unavailable');await database().prepare('UPDATE orders SET payment_id=? WHERE id=?').bind(data.id,order.id).run();return {url:data.url,orderId:order.id};}catch(e){console.error('Stripe session error',e);throw new HttpError('We could not open secure payment. Your pending order is saved in your account. Try again shortly.',503);}
}
export async function completeOrder(orderId:string,status:'paid'|'demo_confirmed',paymentId:string|null){const db=database();const order=await db.prepare('SELECT * FROM orders WHERE id=?').bind(orderId).first<Order>();if(!order||order.status!=='pending')return;const statements=[db.prepare("UPDATE orders SET status=?,payment_id=COALESCE(?,payment_id) WHERE id=? AND status='pending'").bind(status,paymentId,orderId),guard(db,orderId+'-complete'),db.prepare("UPDATE bookings SET status=? WHERE order_id=? AND status='pending'").bind(status==='paid'?'confirmed':'demo_confirmed',orderId)];
 const items=(await db.prepare('SELECT * FROM order_items WHERE order_id=?').bind(orderId).all<{kind:string,quantity:number,price:number,data:string}>()).results;
 for(const item of items)if(item.kind==='gift')for(let i=0;i<item.quantity;i++)statements.push(db.prepare('INSERT INTO gift_cards (code,user_id,order_id,value,balance,status,recipient,created_at,demo) VALUES (?,?,?,?,?,?,?,?,?)').bind('NIM-'+id().replaceAll('-','').slice(0,24).toUpperCase(),order.user_id,orderId,item.price,item.price,'active',item.data,now(),order.demo));
 statements.push(db.prepare('DELETE FROM operation_guards WHERE id=?').bind(orderId+'-complete'));
 try{await db.batch(statements)}catch(e){const current=await db.prepare('SELECT status FROM orders WHERE id=?').bind(orderId).first<{status:string}>();if(current?.status===status)return;throw e;}
 await queueOrderEmails({...order,status});
}
export async function releaseOrder(orderId:string,status='expired'){const db=database();const order=await db.prepare('SELECT * FROM orders WHERE id=?').bind(orderId).first<Order>();if(!order||['expired','cancelled','refunded'].includes(order.status))return;
 const resources=(await db.prepare('SELECT * FROM reservations WHERE order_id=? AND released=0').bind(orderId).all<{id:string,kind:string,resource_id:string,quantity:number}>()).results;
 const statements=[db.prepare('UPDATE orders SET status=? WHERE id=? AND status=?').bind(status,orderId,order.status),guard(db,orderId+'-release')];
 for(const r of resources){statements.push(r.kind==='event'?db.prepare('UPDATE events SET reserved=reserved-? WHERE id=?').bind(r.quantity,r.resource_id):db.prepare('UPDATE variants SET reserved=reserved-? WHERE id=?').bind(r.quantity,r.resource_id));}
 statements.push(db.prepare('UPDATE reservations SET released=1 WHERE order_id=?').bind(orderId),db.prepare('UPDATE bookings SET status=? WHERE order_id=?').bind(status,orderId));
 if(order.gift_applied&&order.gift_code)statements.push(db.prepare('UPDATE gift_cards SET balance=balance+? WHERE code=?').bind(order.gift_applied,order.gift_code));
 statements.push(db.prepare("UPDATE gift_cards SET status='cancelled',balance=0 WHERE order_id=?").bind(orderId),db.prepare('DELETE FROM operation_guards WHERE id=?').bind(orderId+'-release'));
 await db.batch(statements);
}
export async function releaseExpired(){const db=database();const expired=(await db.prepare("SELECT * FROM orders WHERE status='pending' AND expires_at<? LIMIT 10").bind(Date.now()).all<Order>()).results;
 for(const order of expired){if(order.payment_id&&!order.demo){try{const session=await fetch('https://api.stripe.com/v1/checkout/sessions/'+encodeURIComponent(order.payment_id),{headers:{Authorization:'Bearer '+runtimeEnv().STRIPE_SECRET_KEY}}).then(r=>r.json()) as {status:string,payment_status:string};if(session.payment_status==='paid'){await completeOrder(order.id,'paid',null);continue;}if(session.status!=='expired')continue;}catch{continue;}}await releaseOrder(order.id);}}
