export const legalPages:Record<string,{title:string;body:string}>= {
 'privacy':{title:'Privacy policy',body:'This is a draft for founder and professional review before launch. The legal business name, controller contact details, retention schedule and lawful bases must be confirmed.\n\nWe collect the details needed to manage enquiries, bookings, purchases and account preferences. Allergy and accessibility information is optional and must receive additional care because it can reveal health information. Access is restricted to the team arranging the experience.\n\nPrivate photography is provided only where purchased and agreed. Marketing photography permission is separate and optional. Travel information is not automatically sent to a partner.\n\nAccount information and orders are protected by sign in. The full residential venue address is excluded from public pages and APIs. Confirmed guests may receive directions if the business enables this.\n\nThe production data map must identify the hosting, identity, payment, media and email providers, their locations and transfer arrangements. Configure retention and deletion procedures before accepting live customers.\n\nYou can change account preferences and request deletion through My account. The business must confirm its contact details and the process for access, correction, deletion, objection and complaints before launch.'},
 'cookies':{title:'Cookie policy',body:'Draft for review before launch. This preview uses an essential basket cookie for anonymous visitors and platform authentication cookies for account access. A local device preference records your cookie choice.\n\nOptional analytics and marketing trackers are not installed. Analytics remain off unless you choose to allow them. If a provider is added, its cookies, purposes, durations and consent behaviour must be documented here before activation.\n\nYou can change your choice through Cookie preferences in the footer. Blocking essential cookies may prevent your basket or account from working.'},
 'terms':{title:'Terms & conditions',body:'Draft. These are topics to resolve with the founders and a qualified adviser, not final contractual terms. No live purchases should be accepted until this page is approved.\n\nConfirm the legal trading identity, contact details, applicable purchase process, order acceptance, payment methods, pricing and tax treatment.\n\nDefine the scope of each experience, guest conduct, age and supervision requirements, venue arrangements and the handling of significant programme changes.\n\nSet out shop product information, delivery, returns, defective goods, gift card use, membership rules and complaint handling. Mandatory consumer rights must be preserved.\n\nDemo orders do not purchase a real place, product or gift voucher. Travel arrangements are outside the supper club purchase and subject to the independent travel provider’s terms.'},
 'booking-terms':{title:'Booking terms',body:'Draft for review. Final terms must be shown before live payment.\n\nEach event will state its date, UK local start and end time, price, capacity, host, menu and venue arrangements. Advance booking is required. Payment and confirmation rules must be finalised before launch.\n\nThe main adult launch price is £49. Eligible discounts apply to main adult supper club tickets only and do not stack. Membership is checked against the customer account; other evidence may be checked on arrival.\n\nChildren’s tickets are £25. The child age range, supervision arrangements and cooking class minimum ages must be confirmed.\n\nClothing and photography are optional. Clothing selection depends on inventory. Private photography and public marketing permission are separate choices.\n\nTell the host about allergies and dietary needs before booking when severe. Discuss accessibility requirements and the suitability of the venue.\n\nThe founders must approve the cancellation window, no show policy, minimum attendance, event cancellation process and rescheduling arrangements.'},
 'refunds':{title:'Refund & cancellation policy',body:'Draft for professional review. No cancellation periods or refund promises have been finalised.\n\nThe business must publish clear rules for guest cancellations, event cancellations, rescheduling, no shows and any non-refundable elements before selling real tickets. Date-specific experiences and goods can have different requirements.\n\nShop returns, faulty products, personalised photobooks, gift cards and clothing should each be addressed where applicable. Statutory rights must not be limited by an unreviewed policy.\n\nCustomers can request a refund review from their account. A request is not a confirmation that a refund has been approved. Payment-provider confirmation is required before a live order is shown as refunded.'},
 'photography-policy':{title:'Photography policy',body:'Draft for founder and professional review.\n\nThe Cultural Memory Package includes private event photography, applicable portraits, edited digital photographs and a professionally designed 10 page photobook. Production and delivery arrangements will be confirmed by the host.\n\nPurchasing private photography does not grant marketing permission. Marketing photography consent is optional, separate and can be declined without affecting attendance. Each person’s permission must be recorded individually, including the appropriate guardian’s permission for a child.\n\nPrivate galleries must use authenticated access. The business must confirm retention, download access, photobook proof approval, correction requests and any printing provider data sharing before launch.\n\nYou can withdraw recorded marketing permission in your account or contact the business. The founders must document how withdrawal requests are handled for already published or printed material.'},
 'allergens':{title:'Food & allergen information',body:'Please contact the family before booking if you have severe allergies. We cannot promise an allergen free environment.\n\nThe menus in this launch preview are examples. They are not a verified allergen declaration for a real event. Ingredients, supplier information, recipes, preparation methods and cross-contact risks must be checked for every menu.\n\nDuring booking, tell us about allergies, dietary requirements and the guest they relate to. The family must confirm what can be accommodated before accepting a live booking. Vegetarian, vegan and halal labels must only be used after verification.\n\nMenu changes may affect allergens. The event team needs current written information and a process to brief everyone serving food. The final allergen statement and contact details must be approved before launch.'},
 'accessibility':{title:'Accessibility statement',body:'We want your invitation to feel welcoming from the first page.\n\nThe site supports keyboard navigation, visible focus states, labelled forms, adjustable text, screen reader friendly headings and reduced motion preferences. Optional interactions have text alternatives.\n\nThe website has been designed with modern accessibility practices. It has not yet received an independent accessibility audit. Contact the business if something prevents you from using it.\n\nPhysical venue access is separate from website access. Step-free routes, accessible toilets, seating, lighting, transport and assistance arrangements must be confirmed for each location. Tell the host what would help before booking.\n\nThe business must provide a contact method and review date in the final statement.'},
 'membership-terms':{title:'Membership terms',body:'Draft. The Nimontron Circle currently proposes a 15% discount on main adult supper club tickets. This discount cannot be combined with another ticket discount.\n\nHow membership is earned or purchased has not been chosen. Do not assume an annual fee, automatic renewal, spending threshold or lifetime membership.\n\nBefore launch, confirm joining criteria, the start and end of membership, cancellation, renewal, suspension, benefit changes and any member-only shop offers. Future benefits shown on the membership page are ideas, not contractual promises.'},
 'shipping':{title:'Shipping information',body:'Draft. The preview supports collection at an event. Live shipping is disabled until the founders confirm delivery areas, prices, carriers, fulfilment times and lost or damaged parcel handling.\n\nA configurable example delivery charge exists for testing but is not a published shipping offer. Customer addresses must only be collected when needed for a chosen delivery service.\n\nPhotobook delivery arrangements may differ from shop deliveries and should be agreed with the guest separately.'},
 'shop-returns':{title:'Shop returns',body:'Draft for professional review. Before accepting live orders, publish the return process, eligibility, time limits, return delivery arrangements and handling of faulty goods.\n\nAddress clothing, food, customised items and photobooks separately where required. Product-specific exceptions must be clearly explained and reviewed against applicable consumer rights.\n\nNo return address is currently public because the venue may be a private home. The business must provide an appropriate return contact process before launch.'},
 'travel-disclosure':{title:'Travel partner disclosure',body:'Go Plane is the proposed travel partner name. The registered business name, branding, website, services and applicable protections have not yet been verified.\n\nNimontron does not sell travel packages through this site. Travel is arranged independently by the named partner and is subject to that partner’s own terms, prices, booking conditions and protections.\n\nNo travel package prices, financial protections or guarantees are claimed here. The partner’s authorisation to provide each advertised service must be checked before integration.\n\nSubmitting travel interest saves an enquiry for the Nimontron team. No customer data is automatically transferred. Clear consent is required before a future transfer, or guests can choose a direct link to contact the verified partner independently.'},
 'gift-card-terms':{title:'Gift card terms',body:'Draft. The founders must approve gift card validity, redemption, partial use, remaining balances, transfers, lost codes, cancellations and refunds before live sale.\n\nDemo gift cards have no cash value. They can only be used with demo checkout. They cannot be used to purchase other gift cards.\n\nPurchased gift cards appear in the purchaser’s account. A verified email service and agreed delivery arrangements are required before automatic recipient delivery is enabled.'}
};
export const founderItems=[
 ['Business identity','Registered trading name, company or sole trader details and appropriate public correspondence address.'],
 ['Venue','Confirmed launch area, private venue address, capacity, access details, directions, parking and safety arrangements.'],
 ['Food service','Food business registration and operational readiness, insurance, supplier checks, halal sourcing and verified allergen matrix.'],
 ['Confirmed dates','Approve event dates, menu, start and end times, capacity, themes, child age eligibility and class age limits.'],
 ['Sanzida and the family','Genuine biographies, an approved founder portrait, family portraits, kitchen photographs and personal stories.'],
 ['Photography','Image permissions, individual consent process, editing and delivery expectations, photobook supplier, proofing and retention.'],
 ['Clothing and shop','Exact garments, sizes, colours, measurements, product photos, makers, origin, care, ingredients, allergens and real stock.'],
 ['Policies','Professional review of terms, cancellations, refunds, privacy, cookies, photography, gift cards, membership, shipping and returns.'],
 ['Membership','Decide how guests join, duration, any fees, verification, renewal and which future benefits are approved.'],
 ['Payment connection','Provide Stripe credentials and configure verified webhooks, wallet support, refund operation and live payment testing.'],
 ['Email connection','Verified sender domain and provider credentials, recipient consent, delivery testing and reminder scheduling.'],
 ['Travel partner','Verify Go Plane’s exact registered name, website, services, terms, protections, referral terms and enquiry consent process.'],
 ['Contact and social','Confirm email, phone and official social account links. No guessed links are included.'],
 ['Launch review','Replace demo content, verify data protection procedures, test guest and staff flows, approve the accessibility statement and publish indexing settings.']
];
