import {database,id,now,parse,runtimeEnv,getSettings} from './server';
import type {Order} from './types';
export const emailTemplates={confirmation:'Your place at our table',receipt:'Your Nimontron receipt',reminder:'Your dawat is almost here',expect:'A little of what to expect',directions:'Finding Sanzida’s table',dietary:'A final check on dietary requirements',photography:'Your Cultural Memory Package',photobook:'Your photobook update',cooking:'Ready to cook with Sanzida?',clothing:'Your clothing experience',shipping:'Your Nimontron parcel',refund:'Your refund update',membership:'Welcome to the Nimontron Circle',birthday:'A little birthday wish',thanks:'Dhonnobad for joining our table',review:'How was your experience?',recommendations:'Another invitation for you'};
const escape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function emailHtml(title:string,body:string){return `<!doctype html><html lang="en"><body style="margin:0;background:#f7f4eb;font-family:Arial,sans-serif;color:#173d32"><main style="max-width:600px;margin:30px auto;padding:44px"><p style="letter-spacing:3px;font-size:12px">NIMONTRON BY SANZIDA</p><h1 style="font-family:Georgia,serif;font-weight:normal;font-size:38px">${escape(title)}</h1><div style="font-size:16px;line-height:1.8;white-space:pre-line">${escape(body)}</div><hr style="border:0;border-top:1px solid #ccc;margin:35px 0"><p>Come as a guest. Experience Bangladesh. Leave as family.</p></main></body></html>`;}
export async function queueOrderEmails(order:Order){const db=database();const contact=parse<{name:string,email:string}>(order.contact);const s=await getSettings();const status=order.demo?'demo':'queued';const stamp=now();const content=`Hello ${contact.name},\n\n${order.demo?'This is a demo confirmation. No payment was taken and no real seat or product was purchased.':'Thank you for your order. Your payment has been received.'}\n\nYour reference is ${order.reference}.\n\nView your booking, dietary details and updates in your account: ${s.siteUrl}/account\n\n${s.photobookDelivery}\n\nSanzida and the family`;
 const rows=[db.prepare('INSERT OR IGNORE INTO email_outbox (id,user_id,order_id,template,recipient,subject,body,status,scheduled_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(order.id+'-confirmation',order.user_id,order.id,'confirmation',contact.email,emailTemplates.confirmation,content,status,stamp,stamp)];
 const bookings=(await db.prepare('SELECT b.id,e.date,e.start FROM bookings b JOIN events e ON e.id=b.event_id WHERE b.order_id=?').bind(order.id).all<{id:string,date:string,start:string}>()).results;
 for(const b of bookings){const day=new Date(b.date+'T12:00:00Z');day.setUTCDate(day.getUTCDate()-2);const after=new Date(b.date+'T12:00:00Z');after.setUTCDate(after.getUTCDate()+1);for(const [template,scheduled] of [['reminder',day.toISOString()],['thanks',after.toISOString()]]){const body=template==='reminder'?`Your experience is coming up on ${b.date}. Please review your dietary requirements and event details in your account: ${s.siteUrl}/account. Contact the host before attending if anything has changed.`:`Thank you for spending time at our table. Your private photography and photobook updates, if purchased, will appear in your account. We would love to hear about your experience: ${s.siteUrl}/contact.`;rows.push(db.prepare('INSERT OR IGNORE INTO email_outbox (id,user_id,order_id,template,recipient,subject,body,status,scheduled_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(b.id+'-'+template,order.user_id,order.id,template,contact.email,emailTemplates[template as keyof typeof emailTemplates],body,status,scheduled,stamp));}}
 await db.batch(rows);
}
export async function dispatchEmails(){const token=runtimeEnv().RESEND_API_KEY;const from=runtimeEnv().EMAIL_FROM;if(!token||!from)return {sent:0,reason:'Email provider and verified sender need to be connected.'};const db=database();const rows=(await db.prepare("SELECT * FROM email_outbox WHERE status='queued' AND scheduled_at<=? AND attempts<5 LIMIT 20").bind(now()).all<{id:string,recipient:string,subject:string,body:string}>()).results;let sent=0;for(const row of rows){try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':row.id},body:JSON.stringify({from,to:[row.recipient],subject:row.subject,html:emailHtml(row.subject,row.body)})});await db.prepare('UPDATE email_outbox SET attempts=attempts+1,status=? WHERE id=?').bind(response.ok?'sent':'queued',row.id).run();if(response.ok)sent++;}catch{await db.prepare('UPDATE email_outbox SET attempts=attempts+1 WHERE id=?').bind(row.id).run();}}return {sent};}
