import {images} from './config';
import type {EventRecord,Product,Variant,ContentRecord} from './types';
export const foodMoments=[
 {time:'2:00 PM',bangla:'স্বাগতম',title:'Shagotom',subtitle:'A welcome, made personal.',description:'A refreshing welcome drink, something small to nibble and time to settle into the table.'},
 {time:'3:00 PM',bangla:'ফুচকা',title:'The street food moment',subtitle:'A little crunch. A little tang.',description:'Fuchka, chotpoti or jhalmuri. Bright, playful bites inspired by the streets of Bangladesh.'},
 {time:'4:00 PM',bangla:'ভর্তা',title:'A taste of home',subtitle:'The comfort of everyday cooking.',description:'Bhorta, daal and seasonal vegetables. Simple dishes with plenty to say.'},
 {time:'5:30 PM',bangla:'দাওয়াত',title:'The main dawat',subtitle:'Good food is meant to be shared.',description:'Fragrant polao, rich family dishes and generous serving bowls passed from hand to hand.'},
 {time:'7:00 PM',bangla:'চা',title:'Mishti & cha',subtitle:'Stay for one more cup.',description:'Something sweet, a warm cup of Bangladeshi tea and a conversation you do not need to rush.'}
];
export const timeline=[...foodMoments.slice(0,1),{time:'2:30 PM',title:'Meet Bangladesh',description:'A conversational introduction to the country and the stories behind the menu.'},...foodMoments.slice(1,3),{time:'5:00 PM',title:'A moment of culture',description:'Music, language, textiles, stories or a cooking demonstration. Every dawat has its own rhythm.'},...foodMoments.slice(3),{time:'7:30 PM',title:'Make yourself at home',description:'Conversation, photographs and a browse through the shop.'},{time:'8:00 PM',title:'Until next time',description:'Dhonnobad. Thank you for being part of our table.'}];
export const menu=[
 {name:'Fuchka',description:'Crisp shells, chickpeas, potato and tangy tamarind water.',ingredients:'Semolina, flour, chickpeas, potato, tamarind, spices',allergens:['Wheat (gluten)'],dietary:['Vegetarian'],spice:2},
 {name:'Aloo bhorta',description:'Mashed potato, mustard oil, fresh chilli and herbs.',ingredients:'Potato, mustard oil, onion, chilli, coriander',allergens:['Mustard'],dietary:['Vegan'],spice:2},
 {name:'Daal',description:'Gently cooked lentils finished with fragrant spices.',ingredients:'Lentils, onion, garlic, turmeric, oil',allergens:[],dietary:['Vegan'],spice:1},
 {name:'Chicken roast & polao',description:'A celebratory centrepiece with fragrant rice.',ingredients:'Chicken, rice, yoghurt, ghee, onion, spices',allergens:['Milk'],dietary:[],spice:1},
 {name:'Beef kala bhuna',description:'Slowly cooked beef with a deep, rich spice coating.',ingredients:'Beef, onion, mustard oil, spices',allergens:['Mustard'],dietary:[],spice:3},
 {name:'Mishti doi',description:'A small bowl of sweet yoghurt to close the meal.',ingredients:'Milk, yoghurt, sugar',allergens:['Milk'],dietary:['Vegetarian'],spice:0}
];
const eventSpecs=[
 ['old-dhaka-dawat','Old Dhaka Dawat','2026-10-03','Dhaka','An afternoon with the generous spirit of Old Dhaka. Crisp fuchka, fragrant polao and dishes made for a table full of conversation.',images.hero],
 ['sylhet-tea-gardens','Sylhet & the Tea Gardens','2026-10-11','Sylhet','Green hills, warm tea and a table inspired by Sylhet. Discover a different side of Bangladesh, one cup and one story at a time.',images.tea],
 ['village-bangladesh','Village Bangladesh','2026-10-18','Rural Bangladesh','The comfort of home cooking. Bhorta, daal and seasonal dishes bring the everyday generosity of a Bangladeshi family table into focus.',images.river],
 ['dhaka-street-food','Dhaka Street Food','2026-10-24','Dhaka','Tamarind, crunch, spice and chatter. A playful dawat celebrating the street food we reach for when we are out together.',images.street],
 ['winter-pitha-festival','Winter Pitha Festival','2026-11-07','Bangladesh','A seasonal gathering around pitha, warm tea and a generous family meal. Discover the quiet joy of something made by hand.',images.cooking],
 ['bangladeshi-family-sunday','Bangladeshi Family Sunday','2026-11-15','Bangladesh','Bring someone you love, or meet someone new. This family afternoon leaves plenty of room for sharing food, asking questions and feeling at home.',images.hero]
];
const cookingSpecs=[['chicken-roast-polao','Chicken Roast & Polao','2026-10-04','A celebration, from scratch. Learn the spices, timing and careful attention that bring chicken roast and polao together.'],['fuchka-workshop','The Fuchka Workshop','2026-10-17','Build your own crisp, tangy fuchka. Mix the filling, balance tamarind water and discover why one is never enough.'],['bhorta-basics','The Art of Bhorta','2026-10-25','A handful of ingredients, a world of flavour. Discover texture, seasoning and the importance of a confident final taste.'],['pitha-and-cha','Pitha & Cha','2026-11-08','Slow down and make something by hand. An introduction to a seasonal pitha recipe and a cup of tea together.']];
export const seedEvents:EventRecord[]=[...eventSpecs.map((s,i)=>({id:s[0],slug:s[0],title:s[1],type:i===5?'Family event':'Supper club',date:s[2],start:'14:00',end:'20:00',capacity:12,reserved:0,price:4900,image:s[5],description:s[4],region:s[3],theme:s[1],status:'open',menu:JSON.stringify(menu),details:JSON.stringify({host:'Sanzida Musfika Zeem',duration:'6 hours',difficulty:'Everyone welcome',minAge:0,cookingAddon:false}),demo:1,location_id:'uk-launch'})),...cookingSpecs.map((s,i)=>({id:s[0],slug:s[0],title:s[1],type:'Cooking class',date:s[2],start:'11:00',end:'13:00',capacity:6,reserved:0,price:3900,image:i===1?images.street:images.cooking,description:s[3],region:'Sanzida’s kitchen',theme:s[1],status:'open',menu:JSON.stringify(menu.slice(i===1?0:2,i===1?1:4)),details:JSON.stringify({host:'Sanzida Musfika Zeem',duration:'2 hours',difficulty:'Beginner friendly',minAge:16,ingredientsIncluded:true,ageConfirmed:false}),demo:1,location_id:'uk-launch'}))];
const productSpecs:[string,string,string,number,string,string][]=[
 ['forest-panjabi','Forest cotton panjabi','Clothing',2500,images.cloth,'An easy, elegant layer in a deep forest shade.'],['ivory-panjabi','Ivory cotton panjabi','Clothing',2500,images.cloth,'A softly coloured panjabi for a shared table and a special photograph.'],['terracotta-kurta','Terracotta kurta','Clothing',2500,images.cloth,'A warm everyday colour with a relaxed silhouette.'],['classic-saree','Classic woven saree','Clothing',2500,images.cloth,'Discover the drape and detail of a traditional saree.'],['three-piece-outfit','Three piece outfit','Clothing',2500,images.cloth,'A coordinated outfit selected for the cultural clothing experience.'],['woven-scarf','Woven cotton scarf','Clothing',1800,images.cloth,'A light layer with quiet texture and a beautiful woven finish.'],
 ['nakshi-kantha','Nakshi kantha throw','Textiles & crafts',6500,images.craft,'A place for colour, stitch and storytelling in your home.'],['woven-table-runner','Woven table runner','Textiles & crafts',2900,images.cloth,'Bring a little warmth to your own shared table.'],['jute-basket','Jute storage basket','Textiles & crafts',2200,images.craft,'Natural texture for everyday rituals.'],['brass-serving-bowl','Brass serving bowl','Home & table',3400,images.craft,'A warm metallic finish for a table worth gathering around.'],['clay-tea-cups','Clay tea cups, pair','Home & table',1400,images.craft,'A small invitation to pause over a cup of tea.'],['tea-set','The afternoon tea set','Home & table',4200,images.craft,'Set the table for tea and an unhurried conversation.'],['wooden-spice-box','Wooden spice box','Home & table',2800,images.craft,'Keep the flavours you reach for close to hand.'],
 ['sylhet-tea','Sylhet tea collection','Tea & pantry',1200,images.tea,'Tea inspired by the green landscapes of Sylhet.'],['spice-starter','Bangladeshi spice starter','Tea & pantry',1600,images.cooking,'An introduction to the spices in Sanzida’s kitchen.'],['cha-blend','Our cha spice blend','Tea & pantry',800,images.cooking,'Warming notes for your afternoon cup.'],['snack-selection','Street snack selection','Tea & pantry',1000,images.street,'A selection inspired by the savoury snacks of Bangladesh.'],['dawat-gift-box','The dawat gift box','Gifts & stories',4500,images.hero,'A few thoughtful things from the culture behind the table.'],['tea-gift-box','A moment for cha','Gifts & stories',2600,images.tea,'A gift for the person who always stays for tea.'],['river-print','River light print','Gifts & stories',2400,images.river,'A quiet view of Bangladesh to live with every day.'],['dhaka-print','Old Dhaka print','Gifts & stories',2400,images.dhaka,'Architecture, colour and a city full of stories.'],['recipe-notebook','From my kitchen notebook','Gifts & stories',1500,images.cooking,'A place to keep recipes, notes and the little things you learn.'],['traditional-bangles','Traditional bangles','Accessories',1400,images.cloth,'A little colour to finish your outfit.'],['textile-pouch','Woven textile pouch','Accessories',1200,images.craft,'A small piece of texture to take with you.']
];
export const seedProducts:Product[]=productSpecs.map((s,i)=>({id:s[0],slug:s[0],name:s[1],category:s[2],price:s[3],sale_price:null,image:s[4],description:s[5],story:'Selected for the Nimontron collection. The maker, source and full product story will be confirmed before this item goes on sale.',details:JSON.stringify({origin:'Bangladesh intended; supplier verification pending',material:s[2]==='Clothing'?'Cotton specification to be confirmed':'To be confirmed by supplier',weight:'To be confirmed',care:'Final care instructions will accompany the product.',ingredients:s[2]==='Tea & pantry'?'Final ingredients and allergen declaration required before sale.':'Not applicable',allergens:s[2]==='Tea & pantry'?'Unconfirmed. Not available for consumption until verified.':'Not applicable',gallery:[s[4]],video:'',shipping:'Collection at your booked event. Shipping will be confirmed before launch.'}),featured:i%4===0?1:0,active:1,demo:1}));
export const seedVariants:Variant[]=seedProducts.flatMap(p=>(p.category==='Clothing'&&!['classic-saree','woven-scarf'].includes(p.id)?['S','M','L','XL','XXL']:['One size']).map(size=>({id:p.id+'-'+size.toLowerCase().replaceAll(' ','-'),product_id:p.id,label:size,size,colour:p.id.includes('forest')?'Forest':p.id.includes('ivory')?'Ivory':'As shown',stock:8,reserved:0,price:null})));
export const faqs:[string,string][]=[
 ['Do I need to know anything about Bangladesh?','Only that you are welcome. We introduce the food and the stories as we go. Questions are part of the experience.'],
 ['Is this a restaurant?','Nimontron is a family hosted cultural experience. You book a place at a scheduled dawat and share the afternoon with a small group.'],
 ['What does the £49 ticket include?','The main supper club includes the five food moments, cultural activities, family hospitality and time at the shared table. Clothing and photography are optional extras.'],
 ['Can I come on my own?','Absolutely. You can arrive on your own, with a partner or with friends. Meeting people is part of the pleasure of a shared table.'],
 ['How do discounts work?','Members receive 15% off main adult supper club tickets. Students, eligible NHS staff and guests above 60 receive 10% off. We apply only the highest eligible discount. Identification may be checked on arrival.'],
 ['Are children welcome?','Family dates welcome younger guests at £25. The child age range and supervision arrangements will be confirmed before launch. Cooking classes may have their own minimum age.'],
 ['Can you accommodate allergies?','Please contact us before booking if you have severe allergies. Tell us about all allergies and dietary needs during booking. We will discuss what can be accommodated; we do not claim an allergen free environment.'],
 ['Is the food halal?','Halal sourcing and preparation arrangements will be confirmed for each event before bookings go live. Please check the event details or ask the host.'],
 ['Do I have to be photographed?','No. The private photography package is optional. Permission to use your image in marketing is a separate choice, and declining it does not affect your welcome.'],
 ['Do I keep the clothing?','Yes. The £25 clothing experience includes a garment to keep. Type, colour and size depend on the available inventory.'],
 ['Where does the experience take place?','The launch location will be announced before real bookings open. A private home address can be shared only with confirmed guests.'],
 ['What if my plans change?','The cancellation and refund policy is a draft in this preview. Final booking terms will be shown before live payments are enabled.'],
 ['Can you arrange a private gathering?','Tell us your date, group size and idea through the private events form. We can discuss a dawat, a cooking experience or a celebration with clothing and photography.'],
 ['Are the dates on this site confirmed?','This is a working launch preview. The displayed events, inventory and orders are demonstration records. No real ticket or product is sold in demo checkout.']
];
export const articles:ContentRecord[]=[
 {id:'what-is-a-dawat',type:'journal',title:'What makes a meal a dawat?',image:images.hero,published:1,body:'A dawat begins with an invitation. At our table, that invitation is to take your time, try something unfamiliar and let yourself be looked after.\n\nThere is room for a second helping and a question about the dish in front of you. A meal becomes a gathering through the small things: a serving bowl passed along, an introduction, one more cup of tea.\n\nNimontron is built around that feeling. We want to share a little of our Bangladesh, and leave space for you to bring your own stories to the table.',data:JSON.stringify({category:'At our table',readTime:'3 min read',demo:true})},
 {id:'the-fuchka-moment',type:'journal',title:'First, we talk about fuchka.',image:images.street,published:1,body:'A crisp shell. A soft, spiced filling. A spoonful of tangy tamarind water. Fuchka asks for your attention for just a moment before it is gone.\n\nAt the supper club, this is one of our favourite ways to start a conversation. You can compare notes on crunch, spice and just how much tamarind you like.\n\nOur menu rotates, and recipes differ between cooks. Ask Sanzida about the version on your table, or come to a cooking class and learn to build your own.',data:JSON.stringify({category:'Food stories',readTime:'2 min read',demo:true})},
 {id:'stay-for-cha',type:'journal',title:'There is always time for cha.',image:images.tea,published:1,body:'Sometimes the most memorable part of a meal is what happens after the plates have been cleared. The room settles. Someone starts a story. The tea arrives.\n\nAt Nimontron, mishti and cha give the afternoon an unhurried ending. There is no need to know the perfect thing to say. Stay for a cup and let the conversation find its way.\n\nOur Visit Bangladesh page introduces some of the landscapes behind that cup, including the tea country around Sylhet and Srimangal.',data:JSON.stringify({category:'Everyday rituals',readTime:'2 min read',demo:true})},
 {id:'wearing-a-story',type:'journal',title:'A different way to feel at home.',image:images.cloth,published:1,body:'Clothes can start a conversation as easily as food. How is this worn? When would you wear it? What makes this texture or detail special?\n\nThe Bangladeshi Clothing Experience is an invitation to ask those questions. Choose from the available garments, let a host introduce the styling, and wear your choice through the afternoon if you like.\n\nYour garment is yours to keep. If you add the private photography package, it can also become part of the memory you take home.',data:JSON.stringify({category:'Culture & craft',readTime:'3 min read',demo:true})}
];
export const regions=[
 {id:'dhaka',name:'Dhaka',bangla:'ঢাকা',x:90.4125,y:23.8103,image:images.dhaka,subtitle:'A city with an appetite.',text:'Old Dhaka, shared feasts and streets full of life. Discover the setting behind our Old Dhaka Dawat.',foods:'Fuchka · chotpoti · polao',event:'old-dhaka-dawat'},
 {id:'sylhet',name:'Sylhet & Srimangal',bangla:'সিলেট',x:91.8,y:24.6,image:images.tea,subtitle:'A little slower. A little greener.',text:'Tea gardens, green landscapes and time for another cup. Meet a quieter side of Bangladesh.',foods:'Cha · regional family cooking',event:'sylhet-tea-gardens'},
 {id:'chattogram',name:'Chattogram',bangla:'চট্টগ্রাম',x:91.78,y:22.4,image:images.river,subtitle:'Where the hills meet the sea.',text:'A coastal part of Bangladesh with its own food traditions. A place for future supper club stories.',foods:'Kala bhuna · regional dishes',event:'old-dhaka-dawat'},
 {id:'sundarbans',name:'The Sundarbans',bangla:'সুন্দরবন',x:89.55,y:22.1,image:images.forest,subtitle:'Follow the water.',text:'Mangrove landscapes and winding waterways. Explore the country beyond the table with a travel partner when details are confirmed.',foods:'River landscapes · nature stories',event:'village-bangladesh'},
 {id:'rajshahi',name:'Rajshahi',bangla:'রাজশাহী',x:88.65,y:24.38,image:images.cloth,subtitle:'Texture, colour and quiet detail.',text:'A new thread in the story. Discover regional crafts and the people behind the objects we hope to share.',foods:'Seasonal produce · cultural craft',event:'village-bangladesh'}
];
