'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight} from 'lucide-react';
import boundary from '@/lib/bangladesh-boundary.json';
import {regions} from '@/lib/seed';
import {Photo} from './ui';
const project=([lon,lat]:number[])=>[(lon-87.8)*84,(26.7-lat)*86];
function getPolygons(){const b=boundary as unknown as {geometry?:{coordinates:number[][][][]},features?:{geometry:{coordinates:number[][][][]}}[],type:string};return b.geometry?.coordinates||b.features?.[0]?.geometry.coordinates||[];}
const paths=getPolygons().map(poly=>poly.map(ring=>ring.map((p,i)=>{const [x,y]=project(p);return `${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`}).join(' ')+' Z').join(' '));
export function BangladeshMap({content=regions}:{content?:typeof regions}){const [active,setActive]=useState(0);const region=content[active]||regions[0];return <section className="map-section section"><div className="section-heading"><div><p className="eyebrow">ONE COUNTRY. SO MANY STORIES.</p><h2>Where will your<br/><em>curiosity take you?</em></h2></div><p>Get to know a few places behind the food, the crafts and the conversations.</p></div><div className="map-layout"><div className="map-canvas"><span className="map-country-label">BANGLADESH</span><svg viewBox="0 0 500 580" aria-label="Map of Bangladesh with selectable places" role="img"><title>Bangladesh, Natural Earth geographic outline</title>{paths.map((d,i)=><path key={i} d={d} fill="#ced2b8" stroke="#f7f4eb" strokeWidth="1.5"/>)}</svg>{content.map((r,i)=>{const [x,y]=project([r.x,r.y]);return <button key={r.id} className={'map-pin '+(active===i?'active':'')} style={{left:x/500*100+'%',top:y/580*100+'%'}} onClick={()=>setActive(i)} aria-pressed={active===i}><span/><b>{r.name.split(' &')[0]}</b></button>})}<span className="bay-label">BAY OF BENGAL</span></div><article className="region-story" aria-live="polite"><div className="region-image"><Photo src={region.image} alt={region.name+' in Bangladesh'}/><span lang="bn">{region.bangla}</span></div><div className="region-copy"><p className="eyebrow">{String(active+1).padStart(2,'0')} / DISCOVER {region.name.toUpperCase()}</p><h3>{region.subtitle}</h3><p>{region.text}</p><small>{region.foods}</small><Link href={'/events/'+region.event} className="text-link dark">A taste of this story <ArrowUpRight size={18}/></Link></div></article></div><div className="map-accessible-controls" aria-label="Choose a place">{content.map((r,i)=><button key={r.id} aria-pressed={active===i} onClick={()=>setActive(i)}>{r.name}</button>)}</div></section>}
