'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ShoppingBag,UserRound,Menu,ArrowRight} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetTrigger,SheetClose,SheetDescription} from '@/components/ui/sheet';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster} from '@/components/ui/sonner';
import {Check,api} from './ui';
import {toast} from 'sonner';
import type {PublicSettings} from '@/lib/config';
const experienceLinks=[['The supper club','/supper-club'],['Upcoming dates','/events'],['Cooking with Sanzida','/cooking'],['Clothing experience','/clothing'],['Photography experience','/photography'],['Private events','/private-events'],['Gift an experience','/gift-cards']];
const storyLinks=[['Our story','/our-story'],['Meet Sanzida','/meet-sanzida'],['Meet the family','/meet-the-family'],['Food & menu','/food-and-menu'],['Stories from our table','/journal'],['The gallery','/gallery']];
export function Header({settings:s}:{settings:PublicSettings}){const [count,setCount]=useState(0);const [open,setOpen]=useState(false);const pathname=usePathname();useEffect(()=>{const load=()=>api<{cartCount:number}>('session').then(d=>setCount(d.cartCount)).catch(()=>{});load();window.addEventListener('nimontron-cart',load);return()=>window.removeEventListener('nimontron-cart',load)},[]);useEffect(()=>setOpen(false),[pathname]);return <><a className="skip-link" href="#main-content">Skip to content</a><header className="site-header"><nav className="first-nav" aria-label="Main navigation"><Link className="wordmark" href="/" aria-label={s.fullName+' home'}>{s.brand.toLowerCase()}<span>{s.byline.toUpperCase()}</span></Link><div className="nav-links"><DropdownMenu><DropdownMenuTrigger className="nav-dropdown">The experience <span>⌄</span></DropdownMenuTrigger><DropdownMenuContent className="nav-menu">{experienceLinks.map(([t,l])=><DropdownMenuItem key={l} asChild><Link href={l}>{t}</Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger className="nav-dropdown">Our story <span>⌄</span></DropdownMenuTrigger><DropdownMenuContent className="nav-menu">{storyLinks.map(([t,l])=><DropdownMenuItem key={l} asChild><Link href={l}>{t}</Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><Link href="/shop">The shop</Link><Link href="/visit-bangladesh">Discover Bangladesh</Link></div><div className="nav-right"><Link href="/account" className="icon-button account-nav" aria-label="My account"><UserRound size={19}/></Link><Link className="icon-button basket-nav" href="/basket" aria-label={`Basket with ${count} items`}><ShoppingBag size={19}/>{count>0&&<span>{count}</span>}</Link><Link className="button gold small nav-book" href="/events">Find your seat <ArrowUpRight size={16}/></Link><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="icon-button mobile-menu" aria-label="Open menu"><Menu/></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle className="mobile-wordmark">{s.fullName}</SheetTitle><SheetDescription>An invitation to Bangladesh.</SheetDescription><div className="mobile-links">{[['Home','/'],...experienceLinks,...storyLinks,['The shop','/shop'],['Nimontron Circle','/membership'],['Visit Bangladesh','/visit-bangladesh'],['My account','/account'],['Contact','/contact']].map(([t,l])=><SheetClose asChild key={l}><Link href={l}>{t}</Link></SheetClose>)}</div></SheetContent></Sheet></div></nav></header><Toaster position="bottom-right" richColors/></>}
export function Newsletter(){const [email,setEmail]=useState('');const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('enquiry',{type:'newsletter',name:'Nimontron reader',email,consent,data:{}});setDone(true)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}return <div className="newsletter"><p className="eyebrow">A LETTER FROM OUR TABLE</p><h3>Be first to hear<br/>“you’re invited.”</h3><p>New dates, kitchen stories and a little Bangladesh in your inbox.</p>{done?<p role="status" className="success-text">Dhonnobad. You are on our list.</p>:<form onSubmit={submit}><label className="sr-only" htmlFor="newsletter-email">Your email address</label><div className="email-input"><input id="newsletter-email" type="email" placeholder="Your email address" value={email} onChange={e=>setEmail(e.target.value)} required/><button type="submit" aria-label="Join our mailing list" disabled={busy||!consent}><ArrowRight size={20}/></button></div><Check checked={consent} onChange={setConsent} label="Send me news from Nimontron." description="You can unsubscribe by changing your preferences or contacting us."/></form>}</div>}
export function Footer({settings:s}:{settings:PublicSettings}){const [cookieOpen,setCookieOpen]=useState(false);return <><section className="last-invitation"><span lang="bn">নিমন্ত্রণ</span><p className="eyebrow">THERE IS A PLACE FOR YOU HERE</p><h2>Come hungry.<br/><em>Leave a little closer.</em></h2><Link className="button gold" href="/events">Join Sanzida’s table <ArrowUpRight size={19}/></Link></section><footer className="site-footer"><div className="footer-top"><div className="footer-brand"><Link className="wordmark" href="/">{s.brand.toLowerCase()}<span>{s.byline.toUpperCase()}</span></Link><p>{s.tagline}</p><small>A family hosted Bangladeshi cultural experience in the United Kingdom.</small></div><div className="footer-column"><p>AT OUR TABLE</p>{[['Upcoming dates','/events'],['Cooking with Sanzida','/cooking'],['The Nimontron shop','/shop'],['The Nimontron Circle','/membership'],['Private experiences','/private-events'],['Gift cards','/gift-cards']].map(([t,l])=><Link key={l} href={l}>{t}</Link>)}</div><div className="footer-column"><p>STAY CURIOUS</p>{[['Meet the family','/meet-the-family'],['Stories from our table','/journal'],['Visit Bangladesh','/visit-bangladesh'],['The gallery','/gallery'],['Questions & answers','/faqs'],['Contact us','/contact']].map(([t,l])=><Link key={l} href={l}>{t}</Link>)}</div><Newsletter/></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {s.fullName}</span><div><Link href="/privacy">Privacy</Link><button onClick={()=>setCookieOpen(true)}>Cookie preferences</button><Link href="/terms">Terms</Link><Link href="/allergens">Allergens</Link><Link href="/accessibility">Accessibility</Link><Link href="/image-credits">Image credits</Link></div></div><p className="preview-disclosure">{s.demoMode?'Launch preview. Dates, products and availability are demonstration records. No real payments are taken. ':''}Food photographs are temporary illustrative images. Reference photography does not show the founders, their home, actual guests or exact products for sale.</p><div className="footer-social">{([['instagram','Instagram'],['facebook','Facebook'],['youtube','YouTube'],['tiktok','TikTok']] as const).filter(([key])=>s[key]).map(([key,title])=><a key={key} href={s[key]} target="_blank" rel="noopener noreferrer">{title} ↗</a>)}<Link href="/admin">Family admin</Link><Link href="/launch-checklist">Before launch</Link></div></footer><CookiePreferences forceOpen={cookieOpen} setForceOpen={setCookieOpen}/><Link href="/events" className="mobile-booking">Book your seat <ArrowUpRight size={17}/></Link></>}
function CookiePreferences({forceOpen,setForceOpen}:{forceOpen:boolean;setForceOpen:(v:boolean)=>void}){const [banner,setBanner]=useState(false);const [analytics,setAnalytics]=useState(false);useEffect(()=>{try{const saved=localStorage.getItem('nimontron-cookie-choice');setBanner(!saved);if(saved)setAnalytics(JSON.parse(saved).analytics)}catch{setBanner(true)}},[]);function save(value:boolean){try{localStorage.setItem('nimontron-cookie-choice',JSON.stringify({analytics:value,updatedAt:new Date().toISOString()}))}catch{}setBanner(false);setForceOpen(false)}return <>{banner&&<aside className="cookie-banner" aria-label="Cookie preferences"><p>Just the essentials.<span>We use essential cookies to keep your basket and account working. Optional analytics are off.</span></p><div><button onClick={()=>save(false)}>Essential only</button><button onClick={()=>setForceOpen(true)}>Preferences</button></div></aside>}<Dialog open={forceOpen} onOpenChange={setForceOpen}><DialogContent><DialogTitle>Cookie preferences</DialogTitle><DialogDescription>Your choice is saved on this device. No advertising trackers are installed.</DialogDescription><Check label="Essential cookies" checked disabled onChange={()=>{}} description="Needed for account access and your basket."/><Check label="Allow optional analytics" checked={analytics} onChange={setAnalytics} description="No analytics provider is connected in this preview. Your preference will be respected when one is added."/><button className="button" onClick={()=>save(analytics)}>Save preferences</button><Link href="/cookies" className="text-link dark">Read our draft cookie policy</Link></DialogContent></Dialog></>}
