'use client';
import Link from 'next/link';
import {useEffect,useId,useState} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {toast} from 'sonner';
export function Photo({src,alt,className='',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}){const local=src.startsWith('/images/')&&src.endsWith('.webp');return <img className={className} src={src} srcSet={local?`${src.replace('.webp','-640.webp')} 640w, ${src.replace('.webp','-1280.webp')} 1280w, ${src} 1920w`:undefined} sizes="(max-width: 700px) 100vw, (max-width: 1100px) 60vw, 50vw" alt={alt} width="1280" height="900" loading={priority?'eager':'lazy'} decoding="async" fetchPriority={priority?'high':'auto'}/>}
export function Action({href,children,outline=false,gold=false}:{href:string;children:React.ReactNode;outline?:boolean;gold?:boolean}){return <Link className={`button ${outline?'outline':''} ${gold?'gold':''}`} href={href}>{children}<ArrowUpRight size={18}/></Link>}
export function Choice({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(s:string)=>void;options:{value:string;label:string;disabled?:boolean}[];disabled?:boolean}){const id=useId();return <div className="field"><label htmlFor={id}>{label}</label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger id={id} className="choice-trigger"><SelectValue placeholder="Choose an option"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value} disabled={o.disabled}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
export function Check({label,checked,onChange,description,disabled=false}:{label:string;checked:boolean;onChange:(v:boolean)=>void;description?:string;disabled?:boolean}){const id=useId();return <div className="check-row"><Checkbox id={id} checked={checked} onCheckedChange={v=>onChange(v===true)} disabled={disabled}/><div><label htmlFor={id}>{label}</label>{description&&<p>{description}</p>}</div></div>}
export function Field({label,children,hint}:{label:string;children:React.ReactElement;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Counter({label,value,onChange,min=0,max=20}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number}){return <div className="counter-row"><span>{label}</span><div className="counter"><button type="button" onClick={()=>onChange(value-1)} disabled={value<=min} aria-label={`Remove ${label.toLowerCase()}`}>−</button><output aria-live="polite">{value}</output><button type="button" onClick={()=>onChange(value+1)} disabled={value>=max} aria-label={`Add ${label.toLowerCase()}`}>+</button></div></div>}
export function FAQs({items}:{items:[string,string][]}){return <Accordion type="single" collapsible className="faq-list">{items.map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger className="faq-trigger">{q}</AccordionTrigger><AccordionContent className="faq-content">{a}</AccordionContent></AccordionItem>)}</Accordion>}
export function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={'reveal '+className}>{children}</div>}
export function Lightbox({items}:{items:{image:string,title:string,category:string}[]}){const [category,setCategory]=useState('All');const [selected,setSelected]=useState<number|null>(null);const filtered=items.filter(i=>category==='All'||i.category===category);const current=selected!==null?filtered[selected]:null;return <><div className="filter-pills">{['All',...new Set(items.map(i=>i.category))].map(c=><button key={c} onClick={()=>{setCategory(c);setSelected(null)}} className={category===c?'active':''}>{c}</button>)}</div><div className="gallery-grid">{filtered.map((g,i)=><button key={g.image+i} onClick={()=>setSelected(i)} className="gallery-tile" aria-label={'Open photograph: '+g.title}><Photo src={g.image} alt={g.title}/><span>{g.title}</span></button>)}</div><Dialog open={selected!==null} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="lightbox"><DialogTitle>{current?.title}</DialogTitle><DialogDescription>{current?.category} · Temporary collection imagery</DialogDescription>{current&&<Photo src={current.image} alt={current.title}/>}<div className="lightbox-controls"><button className="button outline" onClick={()=>setSelected((selected!-1+filtered.length)%filtered.length)}><ChevronLeft/> Previous</button><button className="button outline" onClick={()=>setSelected((selected!+1)%filtered.length)}>Next <ChevronRight/></button></div></DialogContent></Dialog></>}
export async function api<T=Record<string,unknown>>(path:string,body?:unknown):Promise<T>{const r=await fetch('/api/'+path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {error?:string};if(!r.ok){if(r.status===401)throw new Error('Please sign in through My account to continue.');throw new Error(data.error||'Please try again shortly.');}return data as T;}
export function notifyCart(){window.dispatchEvent(new Event('nimontron-cart'));toast.success('Added to your basket.');}
export function Motion(){useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(node=>observer.observe(node));return()=>observer.disconnect()},[]);return null;}
